### ISSUE TITLE
nonfunctional with 2022.10.0

### ISSUE THREAD

**Issue by TobiTenno** [kbialek/ulauncher-bitwarden#11]
Doesn't seem to recognize the existence of `bw`, `@bitwarden/cli` v2022.10.0

![image](https://user-images.githubusercontent.com/7128721/196593011-9369c015-1721-4aeb-bc75-212f23e8f697.png)

can't manage to screenshot the error, but it reads "Please make sure that bitwarden-cli is installed and accessible"

**Comment by kbialek** [comment]
@TobiTenno Read [this](https://github.com/kbialek/ulauncher-bitwarden/issues/1) Your problem could be very similar to that one.

**Comment by TobiTenno** [comment]
i'm not going to slog my system with snap to use ulauncher... bw is available from everywhere else except this app

**Comment by kbialek** [comment]
There are many ways to install bitwarden cli. The extension expects `bw` binary to be present in the `$PATH` that is available for `ulauncher` process. Let's check if this is actually the problem you have.
You can see `ulauncher` process `$PATH` by running:
```
cat /proc/$(pgrep ulauncher)/environ | tr '\0' '\n' | grep "^PATH="
```
And with this command you can check if `bw` binary is on the ulauncher process `PATH` or not. It will show you either absolute `bw` binary path or nothing when `bw` is not available.
```
export $(cat /proc/$(pgrep ulauncher)/environ | tr '\0' '\n' | grep "^PATH=") && which bw
```
