### ISSUE TITLE
Feature Request - auto connect to bitwarden-cli

### ISSUE THREAD

**Issue by yerbestpal** [kbialek/ulauncher-bitwarden#2]
This is a great extension but not particularly useful if you need to login every time you restart. Some solution to store these details and automatically connect would make for a more fluid experience.

**Comment by kbialek** [comment]
@yerbestpal I'm happy you like it. For max security, the extension is keeping the session token in memory only. If I get your suggestion right, you'd like to store it also somwhere on disk?

**Comment by sergius02** [comment]
Hi! great extension but as @yerbestpal said, typing the credentials every time is sometimes dificult, specially if you have a LARGE password.

Bitwarden CLI has an option to do that:
https://bitwarden.com/help/article/cli/#environment-variable

Is just add an enviroment variable BW_SESSION=SESSION_KEY.

You can add an option to the extension to skip all unlock process.

**Comment by kbialek** [comment]
Hi! @sergius02 you can set "inactivity lock timeout" in the extension preferences page. Then the extension will cache session key in the memory and you won't be forced to unlock the vault on each access.

**Comment by kbialek** [comment]
hey! I guess your use case is that you are mixing ulauncher and cli. To support it I've implemented an option to export the sessionId from ulauncher. Please check out the new release v1.1

**Comment by sergius02** [comment]
Hi! Thats good! :+1:
